apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-production
  namespace: laa-review-criminal-legal-aid-production
data:
  ENV_NAME: production
  RACK_ENV: production
  RAILS_ENV: production
  GOVUK_NOTIFY_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  DATASTORE_API_ROOT: http://service-production.laa-criminal-applications-datastore-production.svc.cluster.local
  OMNIAUTH_AZURE_CLIENT_ID: 7dfb0abc-3b2e-41cf-a2ae-639c5f6b54ba
  OMNIAUTH_AZURE_TENANT_ID: c6874728-71e6-41fe-a9e1-2e8c36776ad8
  OMNIAUTH_AZURE_REDIRECT_URI: https://laa-review-criminal-legal-aid-production.apps.live.cloud-platform.service.justice.gov.uk/users/auth/azure_ad/callback
