apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-production
  namespace: laa-review-criminal-legal-aid-production
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: review-criminal-legal-aid-web-production
