require 'rails_helper'

RSpec.describe 'Viewing supporting evidence' do
  include_context 'with stubbed application'
  include_context 'when downloading a document'

  let(:viewing_enabled) { false }

  before do
    allow(FeatureFlags).to receive(:view_evidence) {
      instance_double(FeatureFlags::EnabledFeature, enabled?: viewing_enabled)
    }

    visit crime_application_path(application_id)
  end

  describe 'showing uploaded evidence' do
    subject(:files_card) do
      page.find('h2.govuk-summary-card__title', text: 'Files')
          .ancestor('div.govuk-summary-card')
    end

    context 'with supporting evidence' do
      it 'shows a link to download the supporting evidence' do
        link_text = 'Download file (pdf, 12 Bytes)'

        within(files_card) do |card|
          expect(card).to have_summary_row 'test.pdf', link_text

          click_link(link_text)
        end
      end

      context 'when viewing evidence is enabled' do
        let(:viewing_enabled) { true }

        include_context 'when viewing a document' do
          it 'navigates to the document viewer when clicking the view link' do
            link_text = 'View'

            within(files_card) do
              click_link(link_text)
              expect(current_path).to eq('/crime-apply-documents-dev/42/WtpJTOwsQ2')
            end
          end
        end

        it 'navigates to the document download when clicking the download link' do
          link_text = 'Download file (pdf, 12 Bytes)'

          within(files_card) do
            click_link(link_text)
            expect(current_path).to eq('/crime-apply-documents-dev/42/WtpJTOwsQ2')
          end
        end
      end
    end

    context 'with no evidence' do
      let(:application_data) do
        super().deep_merge('supporting_evidence' => [], 'evidence_details' => nil)
      end

      it 'shows the files card' do
        within(files_card) do |card|
          expect(card).to have_text 'No files were uploaded'
        end
      end
    end
  end

  context 'with evidence prompt details' do
    it 'shows the supporting evidence section' do
      expect(page).to have_content('Supporting evidence')
    end

    it 'lists evidence prompts generated by Apply' do
      expect(page).to have_content('Other evidence:')
      expect(page).to have_content('their National Insurance number')
    end

    it 'does not have titles for non-existent prompts', :aggregate_failures do # rubocop:disable RSpec/ExampleLength
      [
        "Evidence of their client's income",
        "Evidence of their client's outgoings",
        "Evidence of their client's capital",
        "Evidence of the partners's income",
        "Evidence of the partner's outgoings",
        "Evidence of the partner's capital"
      ].each do |title|
        expect(page).to have_no_content(title)
      end
    end

    it 'adds ruleset data as attributes' do
      nodes = [
        find(:xpath, "//li[@data-evidence-rule-key='national_insurance_32']"),
        find(:xpath, "//li[@data-evidence-rule-id='NationalInsuranceProof']"),
        find(:xpath, "//h2[@data-evidence-last-run-at='2024-04-24T13:28:30+00:00']"),
      ]

      expect(nodes.all?).to be true
    end
  end
end
