require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  # Add custom cops for this project below
  - ./lib/rubocop/custom_cops/govuk_formbuilder/text_field_autocomplete.rb

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'lib/generators/**/*'
    - 'features/**/*'
    - 'vendor/**/*'

####################################
## Customization for this project ##
####################################

# Disabled cops
###############

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

# Enabled but tweaked cops
##########################

# To be tweaked until we find the right balance
Metrics/MethodLength:
  Max: 12

RSpec/ExampleLength:
  Max: 6

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/BlockForwarding
Naming/BlockForwarding:
  EnforcedStyle: explicit

RSpec/MultipleExpectations:
  Max: 2

Rails/SkipsModelValidations:
  Exclude:
    - '**/app/read_models/**/*'
