# Simplify running the application inside a container locally.
# Usage: `docker-compose up`
#
# Do not use docker-compose in production environments.
#
version: '3'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    environment:
      ENV_NAME: staging
      RAILS_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres@db/laa-review-criminal-legal-aid
      SECRET_KEY_BASE: f22760a0bd78a9191ba4c247e23a281cb251461cdba6b5215043ca11b694d734
      DATASTORE_API_ROOT: http://host.docker.internal:3003
      DATASTORE_API_AUTH_SECRET: foobar
      GOVUK_NOTIFY_API_KEY: notify-api-key
      RAILS_SERVE_STATIC_FILES: "1"
      ENABLE_PROMETHEUS_EXPORTER: "false" # can be enabled for quick tests
      PROMETHEUS_EXPORTER_PORT: 9395
      RAILS_LOG_TO_STDOUT: "1"
      DATABASE_SSLMODE: disable
      DISABLE_HTTPS: "1"
      DEV_AUTH_ENABLED: "true"
      IS_LOCAL_DOCKER_ENV: "true"
    ports:
      - "3001:3001" # puma server (rails app)
      - "9395:9395" # prometheus exporter `/metrics` endpoint
    depends_on:
      - db
