# Notify Service Configuration
#
# We use two different Notify environments: "production" and "non-production".
# The production environment is used by the live service, while non-production
# environments are used for testing and development.
#
# The Notify environment is determined by the value of the environment
# variable 'GOVUK_NOTIFY_ENV'. If this variable is not set, the default environment
# is 'non-production'.
#
# The Notify API key, set by "GOVUK_NOTIFY_API_KEY", must correspond to the Notify
# Service of the template set used by the environment.
#
production:
  application_returned_email: 'd0d8768b-2122-40a2-ba01-b4550f36805b'
  access_granted_email: '28ddb4dc-ac53-4298-ad55-ea32bc852ffb'
  onboarding_reply_to_address: 'ab9aa707-25c5-43ea-b079-be65e4aa5765'
  revive_account_email: 'ac8f4f2c-2066-4829-a853-b94323e6c831'
  role_changed_email: 'UNSET'

non-production:
  application_returned_email: 'cfee931f-6588-4814-a2e2-ad025946922f'
  access_granted_email: 'f2704460-a16c-46f0-ab6b-d868421c621a'
  onboarding_reply_to_address: '37a1aa3d-214a-40db-a44a-57a4631536a3'
  revive_account_email: 'c21fcd2d-5135-4b0c-bd36-b412ed07681b'
  role_changed_email: '6f49716f-a478-4adb-a647-53dbe67c52bb'
