feature_flags:
  dev_auth:
    local: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    staging: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    production: false # must never be enabled in the live service
  allow_user_managers_service_access:
    local: false
    staging: true
    production: false # user managers should not access the service in production
  work_stream:
    local: true
    staging: true
    production: true
  means_journey:
    local: true
    staging: true
    production: false
  means_journey:
    local: true
    staging: true
    production: false
