feature_flags:
  dev_auth:
    local: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    staging: <%= ENV.fetch("DEV_AUTH_ENABLED", false) %>
    production: false # must never be enabled in the live service
  allow_user_managers_service_access:
    local: false
    staging: true
    production: false # user managers should not access the service in production
  means_journey:
    local: true
    staging: true
    production: true
  employment_journey:
    local: true
    staging: false
    production: false
  partner_journey:
    local: true
    staging: true
    production: false

# For settings that vary by HostEnv name
host_env_settings:
  phase_banner_tag:
    local: Dev
    staging: Staging
    production: Beta
  default_tag_colour:
    local: green
    staging: orange
    production: blue
