apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-staging
  namespace: laa-review-criminal-legal-aid-staging
data:
  ENV_NAME: staging
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  DATASTORE_API_ROOT: https://criminal-applications-datastore-staging.apps.live.cloud-platform.service.justice.gov.uk
  OMNIAUTH_AZURE_CLIENT_ID: 5d1ba28b-234a-44e1-9464-f5bec5228bfc
  OMNIAUTH_AZURE_TENANT_ID: c6874728-71e6-41fe-a9e1-2e8c36776ad8
  OMNIAUTH_AZURE_REDIRECT_URI: https://laa-review-criminal-legal-aid-staging.apps.live.cloud-platform.service.justice.gov.uk/auth/azure_ad/callback
