apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-staging
  namespace: laa-review-criminal-legal-aid-staging
data:
  ENV_NAME: staging
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  CRIME_APPLY_API_URL: http://service-staging.laa-apply-for-criminal-legal-aid-staging.svc.cluster.local
