apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-staging
  namespace: laa-review-criminal-legal-aid-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ingress-staging-laa-review-criminal-legal-aid-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = 'laa-review-criminal-legal-aid-staging.apps.live.cloud-platform.service.justice.gov.uk') {
        return 301 https://staging.review-criminal-legal-aid.service.justice.gov.uk;
      }
      location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
      }
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyLimit 1048576
      SecRequestBodyNoFilesLimit 1048576
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-apply"
      SecRuleUpdateTargetByTag attack-xss !REQUEST_COOKIES:_laa_review_criminal_legal_aid_session
      SecRuleUpdateTargetByTag attack-sqli !REQUEST_COOKIES:_laa_review_criminal_legal_aid_session
      
      SecRule REQUEST_URI "@beginsWith /api/events" "id:555001, phase:1, pass, t:none, nolog, chain" \
        SecRule REQUEST_METHOD "@streq POST" "chain" \
          SecRule REQUEST_HEADERS:Content-Type "@rx [\s]*text/plain[\s]*" "ctl:ruleRemoveById=920420"
spec:
  ingressClassName: modsec
  tls:
  - hosts:
    - laa-review-criminal-legal-aid-staging.apps.live.cloud-platform.service.justice.gov.uk
  - hosts:
    - staging.review-criminal-legal-aid.service.justice.gov.uk
    secretName: domain-tls-certificate-staging
  rules:
  - host: laa-review-criminal-legal-aid-staging.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-staging
            port:
              number: 80
  - host: staging.review-criminal-legal-aid.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-staging
            port:
              number: 80
